// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: annotations.proto

package gofraconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldConfig carries Gofra-specific metadata on a config proto field.
// Standard concerns use standard mechanisms: descriptions come from proto
// comments, validation from buf/validate annotations.
type FieldConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value applied when no YAML, env, or flag override is present.
	DefaultValue *DefaultValue `protobuf:"bytes,1,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	// Marks the field as containing sensitive data. Secret fields are excluded
	// from CLI flag registration and YAML example generation.
	Secret        *bool `protobuf:"varint,2,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldConfig) Reset() {
	*x = FieldConfig{}
	mi := &file_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConfig) ProtoMessage() {}

func (x *FieldConfig) ProtoReflect() protoreflect.Message {
	mi := &file_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConfig.ProtoReflect.Descriptor instead.
func (*FieldConfig) Descriptor() ([]byte, []int) {
	return file_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *FieldConfig) GetDefaultValue() *DefaultValue {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *FieldConfig) GetSecret() bool {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return false
}

// DefaultValue holds a typed default. The oneof kind must match the proto
// field's scalar type. For repeated string fields, use string_list.
type DefaultValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*DefaultValue_StringValue
	//	*DefaultValue_Int32Value
	//	*DefaultValue_Int64Value
	//	*DefaultValue_BoolValue
	//	*DefaultValue_DoubleValue
	//	*DefaultValue_StringList
	Kind          isDefaultValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultValue) Reset() {
	*x = DefaultValue{}
	mi := &file_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultValue) ProtoMessage() {}

func (x *DefaultValue) ProtoReflect() protoreflect.Message {
	mi := &file_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultValue.ProtoReflect.Descriptor instead.
func (*DefaultValue) Descriptor() ([]byte, []int) {
	return file_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultValue) GetKind() isDefaultValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *DefaultValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*DefaultValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *DefaultValue) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Kind.(*DefaultValue_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *DefaultValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*DefaultValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *DefaultValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*DefaultValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *DefaultValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*DefaultValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *DefaultValue) GetStringList() *StringList {
	if x != nil {
		if x, ok := x.Kind.(*DefaultValue_StringList); ok {
			return x.StringList
		}
	}
	return nil
}

type isDefaultValue_Kind interface {
	isDefaultValue_Kind()
}

type DefaultValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type DefaultValue_Int32Value struct {
	Int32Value int32 `protobuf:"varint,2,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type DefaultValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type DefaultValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type DefaultValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type DefaultValue_StringList struct {
	StringList *StringList `protobuf:"bytes,10,opt,name=string_list,json=stringList,proto3,oneof"`
}

func (*DefaultValue_StringValue) isDefaultValue_Kind() {}

func (*DefaultValue_Int32Value) isDefaultValue_Kind() {}

func (*DefaultValue_Int64Value) isDefaultValue_Kind() {}

func (*DefaultValue_BoolValue) isDefaultValue_Kind() {}

func (*DefaultValue_DoubleValue) isDefaultValue_Kind() {}

func (*DefaultValue_StringList) isDefaultValue_Kind() {}

// StringList is used for repeated string field defaults.
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var file_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldConfig)(nil),
		Field:         51000,
		Name:          "gofra.config.v1.field",
		Tag:           "bytes,51000,opt,name=field",
		Filename:      "annotations.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional gofra.config.v1.FieldConfig field = 51000;
	E_Field = &file_annotations_proto_extTypes[0]
)

var File_annotations_proto protoreflect.FileDescriptor

const file_annotations_proto_rawDesc = "" +
	"\n" +
	"\x11annotations.proto\x12\x0fgofra.config.v1\x1a google/protobuf/descriptor.proto\"\x90\x01\n" +
	"\vFieldConfig\x12G\n" +
	"\rdefault_value\x18\x01 \x01(\v2\x1d.gofra.config.v1.DefaultValueH\x00R\fdefaultValue\x88\x01\x01\x12\x1b\n" +
	"\x06secret\x18\x02 \x01(\bH\x01R\x06secret\x88\x01\x01B\x10\n" +
	"\x0e_default_valueB\t\n" +
	"\a_secret\"\x87\x02\n" +
	"\fDefaultValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint32_value\x18\x02 \x01(\x05H\x00R\n" +
	"int32Value\x12!\n" +
	"\vint64_value\x18\x03 \x01(\x03H\x00R\n" +
	"int64Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12>\n" +
	"\vstring_list\x18\n" +
	" \x01(\v2\x1b.gofra.config.v1.StringListH\x00R\n" +
	"stringListB\x06\n" +
	"\x04kind\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values:V\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xb8\x8e\x03 \x01(\v2\x1c.gofra.config.v1.FieldConfigR\x05field\x88\x01\x01BBZ@github.com/Gabrielbdd/gofra/internal/generate/config/gofraconfigb\x06proto3"

var (
	file_annotations_proto_rawDescOnce sync.Once
	file_annotations_proto_rawDescData []byte
)

func file_annotations_proto_rawDescGZIP() []byte {
	file_annotations_proto_rawDescOnce.Do(func() {
		file_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_annotations_proto_rawDesc), len(file_annotations_proto_rawDesc)))
	})
	return file_annotations_proto_rawDescData
}

var file_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_annotations_proto_goTypes = []any{
	(*FieldConfig)(nil),               // 0: gofra.config.v1.FieldConfig
	(*DefaultValue)(nil),              // 1: gofra.config.v1.DefaultValue
	(*StringList)(nil),                // 2: gofra.config.v1.StringList
	(*descriptorpb.FieldOptions)(nil), // 3: google.protobuf.FieldOptions
}
var file_annotations_proto_depIdxs = []int32{
	1, // 0: gofra.config.v1.FieldConfig.default_value:type_name -> gofra.config.v1.DefaultValue
	2, // 1: gofra.config.v1.DefaultValue.string_list:type_name -> gofra.config.v1.StringList
	3, // 2: gofra.config.v1.field:extendee -> google.protobuf.FieldOptions
	0, // 3: gofra.config.v1.field:type_name -> gofra.config.v1.FieldConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_annotations_proto_init() }
func file_annotations_proto_init() {
	if File_annotations_proto != nil {
		return
	}
	file_annotations_proto_msgTypes[0].OneofWrappers = []any{}
	file_annotations_proto_msgTypes[1].OneofWrappers = []any{
		(*DefaultValue_StringValue)(nil),
		(*DefaultValue_Int32Value)(nil),
		(*DefaultValue_Int64Value)(nil),
		(*DefaultValue_BoolValue)(nil),
		(*DefaultValue_DoubleValue)(nil),
		(*DefaultValue_StringList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_annotations_proto_rawDesc), len(file_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_annotations_proto_goTypes,
		DependencyIndexes: file_annotations_proto_depIdxs,
		MessageInfos:      file_annotations_proto_msgTypes,
		ExtensionInfos:    file_annotations_proto_extTypes,
	}.Build()
	File_annotations_proto = out.File
	file_annotations_proto_goTypes = nil
	file_annotations_proto_depIdxs = nil
}
