package configgen

import (
	"bytes"
	"go/format"
	"text/template"
)

const loadTemplate = `// Code generated by gofra generate config; DO NOT EDIT.
package {{ .GoPackage }}

import (
	runtimeconfig "{{ .RuntimeImport }}"

	flag "github.com/spf13/pflag"
)

// NewFlagSet returns a pflag.FlagSet with CLI flags for all non-secret config
// fields. Flags use dotted key paths matching the YAML structure
// (e.g., --app.port, --public.app_name).
func NewFlagSet() *flag.FlagSet {
	f := flag.NewFlagSet("gofra", flag.ContinueOnError)
{{ range $entry := .Flags }}	f.{{ $entry.Method }}("{{ $entry.Path }}", {{ $entry.Zero }}, "{{ $entry.Desc }}")
{{ end }}	return f
}

// Load reads config using four-layer precedence: struct defaults, YAML file,
// environment variables, and CLI flags.
func Load(args []string, opts ...runtimeconfig.LoadOption) (*Config, error) {
	defaults := []runtimeconfig.LoadOption{runtimeconfig.WithFlags(NewFlagSet())}
	return runtimeconfig.Load(*DefaultConfig(), args, append(defaults, opts...)...)
}
`

type flagEntry struct {
	Method string
	Path   string
	Zero   string
	Desc   string
}

type loadData struct {
	GoPackage     string
	RuntimeImport string
	Flags         []flagEntry
}

// EmitLoad generates load_gen.go: NewFlagSet() and Load().
func EmitLoad(schema *ConfigSchema) ([]byte, error) {
	data := loadData{
		GoPackage:     schema.GoPackage,
		RuntimeImport: schema.RuntimeImport,
	}

	collectFlags(schema.RootMessage, "", &data.Flags)

	tmpl := template.Must(template.New("load").Funcs(templateFuncs).Parse(loadTemplate))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}

	return format.Source(buf.Bytes())
}

func collectFlags(msg *MessageInfo, prefix string, out *[]flagEntry) {
	for _, f := range msg.Fields {
		path := flagPath(prefix, f.KoanfTag)

		if f.IsMessage && f.MessageRef != nil {
			collectFlags(f.MessageRef, path, out)
			continue
		}

		if f.IsSecret || f.IsRepeated || f.FlagType == "" {
			continue
		}

		*out = append(*out, flagEntry{
			Method: f.FlagType,
			Path:   path,
			Zero:   flagZero(f.FlagType),
			Desc:   f.Description,
		})
	}
}

func flagZero(flagType string) string {
	switch flagType {
	case "String":
		return `""`
	case "Int32", "Int64":
		return "0"
	case "Float32", "Float64":
		return "0"
	case "Bool":
		return "false"
	default:
		return `""`
	}
}
