package configgen

import (
	"bytes"
	"go/format"
	"text/template"
)

const configTemplate = `// Code generated by gofra generate config; DO NOT EDIT.
package {{ .GoPackage }}

{{ range .AllMessages }}
{{- if .Description }}// {{ .GoName }} — {{ .Description }}.{{ end }}
type {{ .GoName }} struct {
{{- range .Fields }}
	{{- if .Description }}
	// {{ .Description }}.
	{{- end }}
	{{ .GoName }} {{ .GoType }} {{ structTag . }}
{{- end }}
}
{{ end }}

// DefaultConfig returns a Config with all proto-annotated defaults applied.
func DefaultConfig() *Config {
	return &Config{
{{- range .RootMessage.Fields }}
		{{ .GoName }}: {{ defaultLiteral . }},
{{- end }}
	}
}
`

// EmitConfig generates config_gen.go: Go struct types and DefaultConfig().
func EmitConfig(schema *ConfigSchema) ([]byte, error) {
	funcs := template.FuncMap{}
	for k, v := range templateFuncs {
		funcs[k] = v
	}
	funcs["defaultLiteral"] = func(f FieldInfo) string {
		return renderDefault(f, "")
	}

	tmpl := template.Must(template.New("config").Funcs(funcs).Parse(configTemplate))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, schema); err != nil {
		return nil, err
	}

	return format.Source(buf.Bytes())
}

// renderDefault produces the Go literal for a field's default value.
// For message fields, it recurses into the nested message.
func renderDefault(f FieldInfo, indent string) string {
	if f.IsMessage && f.MessageRef != nil {
		return renderMessageDefault(f.MessageRef, indent)
	}
	if f.Default != nil {
		return f.Default.GoLiteral
	}
	return zeroValue(f)
}

func renderMessageDefault(msg *MessageInfo, indent string) string {
	inner := indent + "\t"
	var buf bytes.Buffer
	buf.WriteString(msg.GoName + "{\n")

	hasAnyDefault := false
	for _, field := range msg.Fields {
		if fieldHasDefault(field) {
			hasAnyDefault = true
			buf.WriteString(inner + "\t" + field.GoName + ": " + renderDefault(field, inner+"\t") + ",\n")
		}
	}

	if !hasAnyDefault {
		return msg.GoName + "{}"
	}

	buf.WriteString(inner + "}")
	return buf.String()
}

func fieldHasDefault(f FieldInfo) bool {
	if f.Default != nil {
		return true
	}
	if f.IsMessage && f.MessageRef != nil {
		for _, child := range f.MessageRef.Fields {
			if fieldHasDefault(child) {
				return true
			}
		}
	}
	return false
}

func zeroValue(f FieldInfo) string {
	if f.IsRepeated {
		return "nil"
	}
	switch f.GoType {
	case "string":
		return `""`
	case "int32", "int64", "uint32", "uint64":
		return "0"
	case "float32", "float64":
		return "0"
	case "bool":
		return "false"
	default:
		return f.GoType + "{}"
	}
}
