package configgen

import (
	"bytes"
	"fmt"
	"strings"
)

// EmitTSPublic returns TypeScript source for the public subtree of the
// config schema. Returns (nil, nil) when the schema has no public subtree
// — the caller can treat that as "skip TS emission".
//
// The emitted file is a single self-contained module with:
//   - `interface` declarations for the public message tree
//   - a `RuntimeConfig` type alias pointing at the top-level public message
//   - a `declare global` Window augmentation for the injected global
//   - a read-only `runtimeConfig` accessor for the common case
//   - a `loadRuntimeConfig()` helper that fails fast when the global is absent
//
// Runtime schema validation is intentionally out of scope for this
// generator; consumers that need it can pair this output with a proto-es
// pipeline.
func EmitTSPublic(schema *ConfigSchema, globalName string) ([]byte, error) {
	if schema == nil || schema.PublicField == nil || schema.PublicField.MessageRef == nil {
		return nil, nil
	}
	if globalName == "" {
		globalName = "__GOFRA_CONFIG__"
	}

	publicMsg := schema.PublicField.MessageRef
	rootType := publicMsg.GoName

	var buf bytes.Buffer
	buf.WriteString("// Code generated by gofra generate config; DO NOT EDIT.\n\n")

	ordered := orderPublicMessages(publicMsg)
	for i, m := range ordered {
		if i > 0 {
			buf.WriteString("\n")
		}
		writeTSInterface(&buf, m)
	}

	fmt.Fprintf(&buf, "\nexport type RuntimeConfig = %s;\n\n", rootType)
	fmt.Fprintf(&buf, "declare global {\n  interface Window {\n    %s?: RuntimeConfig;\n  }\n}\n\n", globalName)
	fmt.Fprintf(&buf, "export const runtimeConfig: Partial<RuntimeConfig> =\n  (typeof window !== \"undefined\" && window.%s) || {};\n\n", globalName)
	fmt.Fprintf(&buf, "export function loadRuntimeConfig(): RuntimeConfig {\n  const cfg = typeof window !== \"undefined\" ? window.%s : undefined;\n  if (!cfg) {\n    throw new Error(\"gofra runtime config unavailable: /_gofra/config.js not loaded\");\n  }\n  return cfg;\n}\n", globalName)

	return buf.Bytes(), nil
}

func orderPublicMessages(root *MessageInfo) []*MessageInfo {
	var result []*MessageInfo
	seen := map[string]bool{}
	var visit func(m *MessageInfo)
	visit = func(m *MessageInfo) {
		if m == nil || seen[m.GoName] {
			return
		}
		// Depth-first so dependencies come first.
		for _, f := range m.Fields {
			if f.IsMessage && f.MessageRef != nil {
				visit(f.MessageRef)
			}
		}
		if seen[m.GoName] {
			return
		}
		seen[m.GoName] = true
		result = append(result, m)
	}
	visit(root)
	return result
}

func writeTSInterface(buf *bytes.Buffer, m *MessageInfo) {
	if desc := strings.TrimSpace(m.Description); desc != "" {
		for _, line := range strings.Split(desc, "\n") {
			fmt.Fprintf(buf, "// %s\n", strings.TrimSpace(line))
		}
	}
	fmt.Fprintf(buf, "export interface %s {\n", m.GoName)
	for _, f := range m.Fields {
		if desc := strings.TrimSpace(f.Description); desc != "" {
			for _, line := range strings.Split(desc, "\n") {
				fmt.Fprintf(buf, "  // %s\n", strings.TrimSpace(line))
			}
		}
		name := f.JSONTag
		if name == "" {
			name = f.ProtoName
		}
		fmt.Fprintf(buf, "  %s: %s;\n", name, tsTypeFor(&f))
	}
	buf.WriteString("}\n")
}

func tsTypeFor(f *FieldInfo) string {
	var base string
	switch {
	case f.IsMessage && f.MessageRef != nil:
		base = f.MessageRef.GoName
	case f.IsMessage:
		base = "unknown"
	default:
		base = goTypeToTSType(f.GoType)
	}
	if f.IsRepeated {
		return base + "[]"
	}
	return base
}

func goTypeToTSType(gt string) string {
	// GoType for scalar repeated fields arrives as "[]string" etc.; strip
	// the slice prefix since IsRepeated appends "[]" in TS separately.
	gt = strings.TrimPrefix(gt, "[]")
	switch gt {
	case "string":
		return "string"
	case "bool":
		return "boolean"
	case "int32", "int64", "uint32", "uint64", "float32", "float64":
		return "number"
	default:
		return "unknown"
	}
}
