package configgen

import (
	"bytes"
	"go/format"
	"text/template"
)

const publicTemplate = `// Code generated by gofra generate config; DO NOT EDIT.
package {{ .GoPackage }}

{{ if .HasPublic }}
import (
	"fmt"
	"net/http"

	runtimeconfig "{{ .RuntimeImport }}"
)

// BindPublicConfig extracts the public config subtree from the full config.
func BindPublicConfig(cfg *Config) (*{{ .PublicType }}, error) {
	if cfg == nil {
		return nil, fmt.Errorf("config: nil *Config")
	}
	return &cfg.{{ .PublicFieldName }}, nil
}

// PublicConfigHandler returns an HTTP handler that serves the public config
// as JavaScript at /_gofra/config.js.
func PublicConfigHandler(
	cfg *Config,
	opts ...runtimeconfig.Option[{{ .PublicType }}],
) http.Handler {
	return runtimeconfig.Handler(
		runtimeconfig.NewResolver(cfg, BindPublicConfig, opts...),
	)
}
{{ end }}
`

type publicData struct {
	GoPackage       string
	RuntimeImport   string
	HasPublic       bool
	PublicType      string
	PublicFieldName string
}

// EmitPublic generates public_gen.go: BindPublicConfig() and PublicConfigHandler().
func EmitPublic(schema *ConfigSchema) ([]byte, error) {
	data := publicData{
		GoPackage:     schema.GoPackage,
		RuntimeImport: schema.RuntimeImport,
	}

	if schema.PublicField != nil {
		data.HasPublic = true
		data.PublicType = schema.PublicField.GoType
		data.PublicFieldName = schema.PublicField.GoName
	}

	tmpl := template.Must(template.New("public").Funcs(templateFuncs).Parse(publicTemplate))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}

	return format.Source(buf.Bytes())
}
